// Copyright (c) 2018 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

// This class implements the IDeviceRegionFinder interface.

const uint32 CDeviceRegionFinder_UID = 99;
