// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CHwFuse
* @{
  Class CHwFuse implements \link IHwFuse \endlink interface.
  
  The class ID `HwFuse` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CHwFuse class.
*/

const uint32 CHwFuse_UID = 28;

/** @} */
