// Copyright (c) 2018 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CIPProtector
* @{
  Class CIPProtector implements \link IIPProtector \endlink interface.
  
  The class ID `IPProtector` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CIPProtector class.
*/

const uint32 CIPProtector_UID = 82;

/** @} */
