// Copyright (c) 2018 Qualcomm Technologies, Inc. All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CKeyManager
* @{
  Class CKeyManager implements \link IKeyManager \endlink interface.

  The class ID `KeyManager` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CKeyManager class.
*/

const uint32 CKeyManager_UID = 110;

/** @} */
