// Copyright (c) 2016 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CMacchiato
* @{
  Class CMacchiato implements \link IMacchiato \endlink interface.
  
  The class ID `Macchiato` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CMacchiato class.
*/

const uint32 CMacchiato_UID = 49;

/** @} */
