// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup COEMBuf
* @{
  Class COEMBuf implements \link IIO \endlink interface.
  
  The class ID `OEMBuf` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the COEMBuf class.
*/

const uint32 COEMBuf_UID = 52;

/** @} */
