// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup COPS
* @{
  Class COPS implements \link IOPS \endlink interface.
  
  The class ID `OPS` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the COPS class.
*/

const uint32 COPS_UID = 90;

/** @} */
