// Copyright (c) 2017 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.


/**
* @addtogroup CPVCLicense
* @{
  Class CPVCLicense implements \link IPVCLicense \endlink interface.
  
  The class ID `PVCLicense` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CPVCLicense class.
*/

// Process the license to enable the PVC interface.

const uint32 CPVCLicense_UID = 34;

/** @} */
