// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CPVC
* @{
  Class CPVC implements \link IPVC \endlink interface.
  
  The class ID `PVC` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CPVC class.
*/

const uint32 CPVC_UID = 14;

/** @} */
