// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CRTICDtb
* @{
  Class CRTICDtb implements \link IRTICDtb \endlink interface.
  
  The class ID `RTICDtb` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CRTICDtb class.
*/

const uint32 CRTICDtb_UID = 112;

/** @} */
