// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CRTICReport
* @{
  Class CRTICReport implements \link IRTICReport \endlink interface.
  
  The class ID `RTICReport` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CRTICReport class.
*/

const uint32 CRTICReport_UID = 98;

/** @} */
