// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CSecureChannel
* @{
  Class CSecureChannel implements \link ISecureChannel \endlink interface.
	
  The class ID `SecureChannel` is included in the default privilege set, therefore the 
  CSecureChannel class is available to every TA.
*/

const uint32 CSecureChannel_UID = 26;

/** @} */
