// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CSecureDisplay
* @{
  Class CSecureDisplay implements \link ISecureDisplay \endlink interface.
  
  The class ID `SecureDisplay` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CSecureDisplay class.
*/

const uint32 CSecureDisplay_UID = 25;

/** @} */
