// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CSPI
* @{
  Class CSPI implements \link ISPI \endlink interface.
  
  The class ID `SPI` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CSPI class.
*/

const uint32 CSPI_UID = 16;

/** @} */
