// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CSync
* @{
  Class CSync implements \link ISync \endlink interface.
  
  The class ID `Sync` is included in the default privilege set, therefore the 
  CSync class is available to every TA.
*/

const uint32 CSync_UID = 51;

/** @} */
