// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/**
* @addtogroup CUptime
* @{
  Class CUptime implements \link IUptime \endlink interface.
  
  The class ID `Uptime` is included in the default privilege set, therefore the 
  CUptime class is available to every TA.
*/

const uint32 CUptime_UID = 18;

/** @} */
