// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.

/** @cond */
interface IValidate {
/** @endcond */

  /**
   * @addtogroup IValidate
   * @{
   */

  /** @cond */
  error ERROR_INVALID;
  /** @endcond */

  /**
    Performs data buffer validation.

    @param[in] data  Data buffer to be validated.

    @return
    Object_OK on success.
  */
  method validate(in buffer data);
  /** @} */ /* end_addtogroup IValidate */
};
