#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017,2023 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#

. /lib/wifi/wifi-utils.sh

START=13

WPAD_VARRUN="$(get_wpad_var_run)"

start_service() {
	local cert_enabled="$(is_cert_enabled)"

	procd_open_instance $PKG_NAME
	procd_set_param command /usr/sbin/hostapd -g $WPAD_VARRUN/hostapd/global -B -P $WPAD_VARRUN/hostapd-global.pid -f /tmp/hostapd.txt
	procd_set_param stdout 1
	procd_set_param stderr 1
	[ "${cert_enabled}" -eq 0 -a -x /sbin/ujail -a -e /etc/capabilities/wpad.json ] && {
		if [ ! -d $WPAD_VARRUN ]; then
			mkdir -p $WPAD_VARRUN
		fi
		chown wifi:wifi $WPAD_VARRUN
		procd_add_jail $PKG_NAME
		procd_set_param user wifi
		procd_set_param group wifi
		procd_set_param capabilities /etc/capabilities/wpad.json
	}
	procd_close_instance
}

stop_service() {
	if  [ -e $WPAD_VARRUN/hostapd-global.pid ]
	then
		kill $(cat $WPAD_VARRUN/hostapd-global.pid) &> /dev/null
		rm $WPAD_VARRUN/hostapd-global.pid &> /dev/null
	fi
}

reload_service() {
	stop
	start
}

restart() {
	stop
	start
}

boot_hostapd() {
	if  [ -e "$WPAD_VARRUN/hostapd-global.pid" ]
	then
		kill $(cat $WPAD_VARRUN/hostapd-global.pid) &> /dev/null
		rm $WPAD_VARRUN/hostapd-global.pid &> /dev/null
	fi
	ulimit -c unlimited
	hostapd -g $WPAD_VARRUN/hostapd/global -B -P $WPAD_VARRUN/hostapd-global.pid -f tmp/hostapd.txt
	# Set hostapd OOM score to -1000 to prevent it from getting killed
	echo -1000 > /proc/$(cat $WPAD_VARRUN/hostapd-global.pid)/oom_score_adj

}

[ -f /tmp/sysinfo/sdk_board_name ] && {
	board_name=ap$(cat /tmp/sysinfo/sdk_board_name | awk -F 'ap' '{print$2}')
}

case "$board_name" in
ap-sdxpinn*)
	USE_PROCD=1
	PROCD_DEBUG=1
	SVC_NAME=hostapd
	PKG_NAME=qca-hostapd
;;
*)
	boot() {
		boot_hostapd &
	}
;;
esac
