#!/bin/sh
: '
Copyright (c) 2024 Qualcomm Technologies, Inc.
All Rights Reserved.
Confidential and Proprietary - Qualcomm Technologies, Inc.

'

SERVER=$(fw_printenv serverip | cut -c10-24);

if [ ! -n "$SERVER" ]; then
	printf "%s\n" "Wrong configuaration SERVER = $SERVER" > /dev/console
	exit 0
fi

NETSTAT=0

if [ -e /dev/$DEVICENAME ] && [ "$ACTION" = add ]; then
	cd /dev
	REMOTE="minidump2mem.bin"

	while [ $NETSTAT -ne 1 ]; do
		ping -c 3 $SERVER
		if [ $? -eq  0 ]; then
			NETSTAT=1;
		else
			sleep 10
		fi
	done

	printf "%s\n" "Collecting $REMOTE dump in $SERVER" > /dev/console
	$(tftp -l $DEVICENAME -r $REMOTE -p $SERVER 2>&1)
	if [ $? -eq 0 ]; then
		printf "%s\n" "$REMOTE dump collected in $SERVER" \
								> /dev/console
	else
		printf "%s\n" "$REMOTE dump collection failed in $SERVER" \
								> /dev/console
	fi
	cd /
fi
