SSID: FH,__FH_SSID_REPLACE__,__FH_AUTH_TYPE_REPLACE__,0x0008,__FH_KEY_REPLACE__,0,1
SSID: BH,__BH_SSID_REPLACE__,__BH_AUTH_TYPE_REPLACE__,0x0008,__BH_KEY_REPLACE__,1,0
SSID: FHA1,__FHA1_SSID_REPLACE__,__FHA1_AUTH_TYPE_REPLACE__,0x0008,__FHA1_KEY_REPLACE__,0,1
SSID: FHA2,__FHA2_SSID_REPLACE__,__FHA2_AUTH_TYPE_REPLACE__,0x0008,__FHA2_KEY_REPLACE__,0,1
SSID: FHA3,__FHA3_SSID_REPLACE__,__FHA3_AUTH_TYPE_REPLACE__,0x0008,__FHA3_KEY_REPLACE__,0,1
MLO: MLD0,__MLD0_SSID_KEY_REPLACE__
MLO: MLD1,__MLD1_SSID_KEY_REPLACE__
MLO: MLD2,__MLD2_SSID_KEY_REPLACE__
MLO: MLD3,__MLD3_SSID_KEY_REPLACE__
MLO: MLD4,__MLD4_SSID_KEY_REPLACE__
MLO: MLD5,__MLD5_SSID_KEY_REPLACE__
MLO: MLD6,__MLD6_SSID_KEY_REPLACE__
MLO: MLD7,__MLD7_SSID_KEY_REPLACE__
Generic-Policy: 2,115,120,121,127,F,FH,BH,FHA1,FHA2,FHA3
Generic-Policy: 1,80,89,F,FH,BH,FHA1,FHA2,FHA3
Generic-Policy: 1,115,120,L,FH,FHA1,FHA2,FHA3
Generic-Policy: 1,121,127,H,BH
Generic-Policy: 1,131,136,F,FH,BH,FHA1,FHA2,FHA3
Generic-Policy: 1,131,136,L,BH
Generic-Policy: 1,131,136,H,FH,BH,FHA1,FHA2,FHA3
MLO-Policy: 2,115,120,121,127,F,MLD05G,MLD15G,MLD25G,MLD35G,MLD45G,MLD55G,MLD65G,MLD75G
MLO-Policy: 1,80,89,F,MLD02G,MLD12G,MLD22G,MLD32G,MLD42G,MLD52G,MLD62G,MLD72G
MLO-Policy: 1,115,120,L,MLD05GL,MLD15GL,MLD25GL,MLD35GL,MLD45GL,MLD55GL,MLD65GL,MLD75GL
MLO-Policy: 1,121,127,H,MLD05G,MLD15G,MLD25G,MLD35G,MLD45G,MLD55G,MLD65G,MLD75G
MLO-Policy: 1,131,136,F,MLD06G,MLD16G,MLD26G,MLD36G,MLD46G,MLD56G,MLD66G,MLD76G
MLO-Policy: 1,131,136,H,MLD06G,MLD16G,MLD26G,MLD36G,MLD46G,MLD56G,MLD66G,MLD76G
MLO-Policy: 1,131,136,L,MLD06GL,MLD16GL,MLD26GL,MLD36GL,MLD46GL,MLD56GL,MLD66GL,MLD76GL
