/*===========================================================================

FILE:        u_data.c

DESCRIPTION: This file implements the target-specific icb micro driver data

   Copyright (c) 2018 QUALCOMM Technologies, Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary
-------------------------------------------------------------------------------

$Header: //components/rel/core.tzw/1.2/settings/systemdrivers/icb/config/90xx/u_data.c#1 $ 
$DateTime: 2020/12/21 07:48:18 $
$Author: pwbldsvc $
$Change: 27890791 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: Trustzone
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2018/04/13 Autogen  Autogenerated version

=============================================================================*/
#include "icbuarb.h"
#include "icbuarbi.h"
#include "comdef.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        MASTER DECLARATIONS
============================================================================*/
/* APPS_PROC */
static icb_master master_apps_proc =
{
  ICBID_MASTER_APPSS_PROC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_BIMC_1 */
static icb_master master_snoc_bimc_1 =
{
  ICBID_MASTER_SNOC_BIMC_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* CRYPTO_C0 */
static icb_master master_crypto_c0 =
{
  ICBID_MASTER_CRYPTO_CORE0,
  { 
    0
  },
  true, /* remote node? */
  650, /* width in bytes */
  0,
  NULL,
};

/* BLSP_1 */
static icb_master master_blsp_1 =
{
  ICBID_MASTER_BLSP_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BLSP_2 */
static icb_master master_blsp_2 =
{
  ICBID_MASTER_BLSP_2,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* CR_VIRT_PCNOC */
static icb_master master_cr_virt_pcnoc =
{
  ICBID_MASTER_CRVIRT_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_PCNOC */
static icb_master master_snoc_pcnoc =
{
  ICBID_MASTER_SNOC_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_2 */
static icb_master master_pcnoc_int_2 =
{
  ICBID_MASTER_PCNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_3 */
static icb_master master_pcnoc_int_3 =
{
  ICBID_MASTER_PCNOC_INT_3,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_0 */
static icb_master master_pcnoc_s_0 =
{
  ICBID_MASTER_PCNOC_S_0,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_6 */
static icb_master master_pcnoc_s_6 =
{
  ICBID_MASTER_PCNOC_S_6,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_8 */
static icb_master master_pcnoc_s_8 =
{
  ICBID_MASTER_PCNOC_S_8,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_9 */
static icb_master master_pcnoc_s_9 =
{
  ICBID_MASTER_PCNOC_S_9,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BIMC_SNOC */
static icb_master master_bimc_snoc =
{
  ICBID_MASTER_BIMC_SNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_SNOC */
static icb_master master_pcnoc_snoc =
{
  ICBID_MASTER_PNOC_SNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_INT_1 */
static icb_master master_snoc_int_1 =
{
  ICBID_MASTER_SNOC_INT_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_INT_2 */
static icb_master master_snoc_int_2 =
{
  ICBID_MASTER_SNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};


/*============================================================================
                        SLAVE DECLARATIONS
============================================================================*/
/* EBI */
static icb_slave slave_ebi =
{
  ICBID_SLAVE_EBI1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* BIMC_SNOC */
static icb_slave slave_bimc_snoc =
{
  ICBID_SLAVE_BIMC_SNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PRNG */
static icb_slave slave_prng =
{
  ICBID_SLAVE_PRNG,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BLSP_1 */
static icb_slave slave_blsp_1 =
{
  ICBID_SLAVE_BLSP_1,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* BLSP_2 */
static icb_slave slave_blsp_2 =
{
  ICBID_SLAVE_BLSP_2,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* CRYPTO_0_CFG */
static icb_slave slave_crypto_0_cfg =
{
  ICBID_SLAVE_CRYPTO_0_CFG,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_SNOC */
static icb_slave slave_pcnoc_snoc =
{
  ICBID_SLAVE_PCNOC_SNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_2 */
static icb_slave slave_pcnoc_int_2 =
{
  ICBID_SLAVE_PCNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_INT_3 */
static icb_slave slave_pcnoc_int_3 =
{
  ICBID_SLAVE_PCNOC_INT_3,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_0 */
static icb_slave slave_pcnoc_s_0 =
{
  ICBID_SLAVE_PCNOC_S_0,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_6 */
static icb_slave slave_pcnoc_s_6 =
{
  ICBID_SLAVE_PCNOC_S_6,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_8 */
static icb_slave slave_pcnoc_s_8 =
{
  ICBID_SLAVE_PCNOC_S_8,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* PCNOC_S_9 */
static icb_slave slave_pcnoc_s_9 =
{
  ICBID_SLAVE_PCNOC_S_9,
  { 
    0
  },
  true, /* remote node? */
  4, /* width in bytes */
  0,
  NULL,
};

/* SNOC_BIMC_1 */
static icb_slave slave_snoc_bimc_1 =
{
  ICBID_SLAVE_SNOC_BIMC_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* IMEM */
static icb_slave slave_imem =
{
  ICBID_SLAVE_IMEM,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_PCNOC */
static icb_slave slave_snoc_pcnoc =
{
  ICBID_SLAVE_SNOC_PCNOC,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_INT_1 */
static icb_slave slave_snoc_int_1 =
{
  ICBID_SLAVE_SNOC_INT_1,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/* SNOC_INT_2 */
static icb_slave slave_snoc_int_2 =
{
  ICBID_SLAVE_SNOC_INT_2,
  { 
    0
  },
  true, /* remote node? */
  8, /* width in bytes */
  0,
  NULL,
};

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/
static icb_pair route_apps_proc_blsp_1_hops[6] =
{
  {
    &master_apps_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_int_1
  },
  {
    &master_snoc_int_1,
    &slave_snoc_pcnoc
  },
  {
    &master_snoc_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_s_6
  },
  {
    &master_pcnoc_s_6,
    &slave_blsp_1
  },
};

static icb_route route_apps_proc_blsp_1 =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_BLSP_1,
  6,
  route_apps_proc_blsp_1_hops
};
 
static icb_pair route_apps_proc_blsp_2_hops[6] =
{
  {
    &master_apps_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_int_1
  },
  {
    &master_snoc_int_1,
    &slave_snoc_pcnoc
  },
  {
    &master_snoc_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_s_9
  },
  {
    &master_pcnoc_s_9,
    &slave_blsp_2
  },
};

static icb_route route_apps_proc_blsp_2 =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_BLSP_2,
  6,
  route_apps_proc_blsp_2_hops
};
 
static icb_pair route_apps_proc_crypto_0_cfg_hops[6] =
{
  {
    &master_apps_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_int_1
  },
  {
    &master_snoc_int_1,
    &slave_snoc_pcnoc
  },
  {
    &master_snoc_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_s_8
  },
  {
    &master_pcnoc_s_8,
    &slave_crypto_0_cfg
  },
};

static icb_route route_apps_proc_crypto_0_cfg =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_CRYPTO_0_CFG,
  6,
  route_apps_proc_crypto_0_cfg_hops
};
 
static icb_pair route_apps_proc_ebi_hops[1] =
{
  {
    &master_apps_proc,
    &slave_ebi
  },
};

static icb_route route_apps_proc_ebi =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_EBI1,
  1,
  route_apps_proc_ebi_hops
};
 
static icb_pair route_apps_proc_imem_hops[4] =
{
  {
    &master_apps_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_int_1
  },
  {
    &master_snoc_int_1,
    &slave_snoc_int_2
  },
  {
    &master_snoc_int_2,
    &slave_imem
  },
};

static icb_route route_apps_proc_imem =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_IMEM,
  4,
  route_apps_proc_imem_hops
};
 
static icb_pair route_apps_proc_prng_hops[6] =
{
  {
    &master_apps_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_int_1
  },
  {
    &master_snoc_int_1,
    &slave_snoc_pcnoc
  },
  {
    &master_snoc_pcnoc,
    &slave_pcnoc_int_2
  },
  {
    &master_pcnoc_int_2,
    &slave_pcnoc_s_0
  },
  {
    &master_pcnoc_s_0,
    &slave_prng
  },
};

static icb_route route_apps_proc_prng =
{

  ICBID_MASTER_APPSS_PROC,
  ICBID_SLAVE_PRNG,
  6,
  route_apps_proc_prng_hops
};
 
static icb_pair route_blsp_1_ebi_hops[4] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_bimc_1
  },
  {
    &master_snoc_bimc_1,
    &slave_ebi
  },
};

static icb_route route_blsp_1_ebi =
{

  ICBID_MASTER_BLSP_1,
  ICBID_SLAVE_EBI1,
  4,
  route_blsp_1_ebi_hops
};
 
static icb_pair route_blsp_1_imem_hops[4] =
{
  {
    &master_blsp_1,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_int_2
  },
  {
    &master_snoc_int_2,
    &slave_imem
  },
};

static icb_route route_blsp_1_imem =
{

  ICBID_MASTER_BLSP_1,
  ICBID_SLAVE_IMEM,
  4,
  route_blsp_1_imem_hops
};
 
static icb_pair route_blsp_2_ebi_hops[4] =
{
  {
    &master_blsp_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_bimc_1
  },
  {
    &master_snoc_bimc_1,
    &slave_ebi
  },
};

static icb_route route_blsp_2_ebi =
{

  ICBID_MASTER_BLSP_2,
  ICBID_SLAVE_EBI1,
  4,
  route_blsp_2_ebi_hops
};
 
static icb_pair route_blsp_2_imem_hops[4] =
{
  {
    &master_blsp_2,
    &slave_pcnoc_int_3
  },
  {
    &master_pcnoc_int_3,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_int_2
  },
  {
    &master_snoc_int_2,
    &slave_imem
  },
};

static icb_route route_blsp_2_imem =
{

  ICBID_MASTER_BLSP_2,
  ICBID_SLAVE_IMEM,
  4,
  route_blsp_2_imem_hops
};
 
static icb_pair route_crypto_c0_ebi_hops[4] =
{
  {
    &master_crypto_c0,
    NULL
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_bimc_1
  },
  {
    &master_snoc_bimc_1,
    &slave_ebi
  },
};

static icb_route route_crypto_c0_ebi =
{

  ICBID_MASTER_CRYPTO_CORE0,
  ICBID_SLAVE_EBI1,
  4,
  route_crypto_c0_ebi_hops
};
 
static icb_pair route_crypto_c0_imem_hops[4] =
{
  {
    &master_crypto_c0,
    NULL
  },
  {
    &master_cr_virt_pcnoc,
    &slave_pcnoc_snoc
  },
  {
    &master_pcnoc_snoc,
    &slave_snoc_int_2
  },
  {
    &master_snoc_int_2,
    &slave_imem
  },
};

static icb_route route_crypto_c0_imem =
{

  ICBID_MASTER_CRYPTO_CORE0,
  ICBID_SLAVE_IMEM,
  4,
  route_crypto_c0_imem_hops
};
 
/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
static icb_route *icb_route_list[12] =
{
  &route_apps_proc_blsp_1,
  &route_apps_proc_blsp_2,
  &route_apps_proc_crypto_0_cfg,
  &route_apps_proc_ebi,
  &route_apps_proc_imem,
  &route_apps_proc_prng,
  &route_blsp_1_ebi,
  &route_blsp_1_imem,
  &route_blsp_2_ebi,
  &route_blsp_2_imem,
  &route_crypto_c0_ebi,
  &route_crypto_c0_imem,
};

const icb_info info =
{
  12,
  icb_route_list,
  0,
  NULL,
};
