#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017, 2024 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

START=98

start_diag_app()
{
        #local serverip=`grep -oh "serverip.*#"  /proc/cmdline  | awk -F '#' '{print $2}'`
        local serverip="192.168.10.100"
        local diag_socket_log_path="/usr/sbin/diag_socket_log"
        if [ -f "$diag_socket_log_path" ]; then
                /usr/sbin/diag_socket_log -a $serverip &
                echo "/usr/sbin/diag_socket_log $serverip started" > /dev/kmsg
        else
                /usr/sbin/diag_socket_app -a $serverip &
                echo "/usr/sbin/diag_socket_app $serverip started" > /dev/kmsg
        fi
}

start() {
	is_ftm=`grep wifi_ftm_mode /proc/cmdline | wc -l`
	[ $is_ftm = 0 ] && is_ftm=`/sbin/is_nocal`
	[ $is_ftm = 1 ] && start_diag_app
}

