#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /lib/functions.sh
. /usr/share/libubox/jshn.sh

usage() {
	cat <<EOF
Usage: $0 [config|up|down|reload|status]
enables (default), disables or configures devices not yet configured.
EOF
	exit 1
}

ubus_wifi_cmd() {
	local cmd="$1"
	local dev="$2"

	ubus list | grep -q 'network.wireless' && {
		json_init
		[ -n "$2" ] && json_add_string device "$2"
		ubus call network.wireless "$1" "$(json_dump)"
	}
}

find_net_config() {(
	local vif="$1"
	local cfg
	local ifname
	local mode

	config_get mode "$vif" mode
	if [ x"$(uci -q get system.board.type)" == x"router" -o x"$mode" == x"sta" ]; then
		config_get cfg "$vif" network
	else
		ifstatus wan | grep up | grep -q true
		if [ "$?" -eq 0 ]; then
			cfg="wan"
		else
			cfg="lan"
		fi
	fi

	[ -z "$cfg" ] && {
		include /lib/network
		scan_interfaces

		config_get ifname "$vif" ifname

		cfg="$(find_config "$ifname")"
	}
	[ -z "$cfg" ] && return 0
	echo "$cfg"
)}


bridge_interface() {(
	local cfg="$1"
	[ -z "$cfg" ] && return 0

	include /lib/network
	scan_interfaces

	for cfg in $cfg; do
		config_get iftype "$cfg" type
		[ "$iftype" = bridge ] && config_get "$cfg" ifname
		prepare_interface_bridge "$cfg"
		return $?
	done
)}

prepare_key_wep() {
	local key="$1"
	local hex=1

	echo -n "$key" | grep -qE "[^a-fA-F0-9]" && hex=0
	[ "${#key}" -eq 10 -a $hex -eq 1 ] || \
	[ "${#key}" -eq 26 -a $hex -eq 1 ] || \
	[ "${#key}" -eq 32 -a $hex -eq 1 ] || {
		[ "${key:0:2}" = "s:" ] && key="${key#s:}"
		key="$(echo -n "$key" | hexdump -ve '1/1 "%02x" ""')"
	}
	echo "$key"
}

wifi_fixup_hwmode() {
	local device="$1"
	local default="$2"
	local hwmode hwmode_11n

	config_get channel "$device" channel
	config_get hwmode "$device" hwmode
	case "$hwmode" in
		11ad) hwmode=ad;;
		11bg) hwmode=bg;;
		11a) hwmode=a;;
		11b) hwmode=b;;
		11g) hwmode=g;;
		11n*)
			hwmode_11n="${hwmode##11n}"
			case "$hwmode_11n" in
				a|g) ;;
				default) hwmode_11n="$default"
			esac
			config_set "$device" hwmode_11n "$hwmode_11n"
		;;
		*)
			hwmode=
			if [ "${channel:-0}" -gt 0 ]; then
				if [ "${channel:-0}" -gt 14 ]; then
					hwmode=a
				else
					hwmode=g
				fi
			else
				hwmode="$default"
			fi
		;;
	esac
	config_set "$device" hwmode "$hwmode"
}

_wifi_updown() {
	for driver in ${DRIVERS}; do (
		if eval "type pre_${driver}" 2>/dev/null >/dev/null; then
			eval "pre_${driver} ${1} '$2' '$3' '$4' '$5'"
		fi
	); done

	for device in ${2:-$DEVICES}; do (
		config_get disabled "$device" disabled
		[ "$disabled" = "1" ] && {
			echo "'$device' is disabled"
			set disable
		}
		config_get iftype "$device" type
		if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
			eval "scan_$iftype '$device'"
			eval "${1}_$iftype '$device' '$3'" || echo "$device($iftype): ${1} failed"
		elif [ ! -f /lib/netifd/wireless/$iftype.sh ]; then
			echo "$device($iftype): Interface type not supported"
		fi
	); done

	for driver in ${DRIVERS}; do (
		if eval "type post_${driver}" 2>/dev/null >/dev/null; then
			eval "post_${driver} ${1} '$2' '$3'"
		fi
	); done
}

wifi_done() {
	#DONE
	/etc/init.d/vlan restart
	return 0
}

wifi_updown() {
	cmd=down
	[ enable = "$1" ] && {
		_wifi_updown disable "$2" "$3"
		ubus_wifi_cmd "$cmd" "$2"
		scan_wifi
		cmd=up
	}
	ubus_wifi_cmd "$cmd" "$2"
	_wifi_updown "$@"
	wifi_done
}

wifi_reload_legacy() {
	_wifi_updown "disable" "$1" "$2" "$3" "$4"
	scan_wifi
	_wifi_updown "enable" "$1" "$2" "$3" "$4"
	wifi_done
}

wifi_reload() {
	ubus call network reload
	wifi_reload_legacy "" "$2"
}

wifi_iface() {
	for device in $DEVICES; do
		config_get iftype "$device" type
		config_get vifs "$device" vifs
		for vif in $vifs; do
			[ "$vif" = "$2" ] && {
				if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
					eval "${1}_$iftype '$vif'" || echo "$vif($iftype): ${1} failed"
				else
					echo "$vif($iftype): Interface type not supported"
				fi
				return 0
			}
		done
	done
	return 1
}

wifi_detect() {
	for driver in ${1:-$DRIVERS}; do (
		if eval "type detect_$driver" 2>/dev/null >/dev/null; then
			eval "detect_$driver" || echo "$driver: Detect failed" >&2
		else
			echo "$driver: Hardware detection not supported" >&2
		fi
	); done
}

wifi_config() {
	[ ! -f /etc/config/wireless ] && touch /etc/config/wireless

	for driver in $DRIVERS; do (
		if eval "type detect_$driver" 2>/dev/null >/dev/null; then
			eval "detect_$driver" "$1" || echo "$driver: Detect failed" >&2
		else
			echo "$driver: Hardware detection not supported" >&2
		fi
	); done
}

wifi_unload() {
	local iftype
	_wifi_updown "disable" "$1"
	[ -n "$1" ] && config_get iftype "$1" type
	for driver in ${iftype:-$DRIVERS}; do (
		if eval "type unload_$driver" 2>/dev/null >/dev/null; then
			eval "unload_$driver" || echo "$driver: unload failed" >&2
		else
			echo "$driver: wifi unload not supported" >&2
		fi
	); done
}

wifi_load() {
	local iftype
	wifi_unload "$1"
	[ -n "$1" ] && config_get iftype "$1" type
	for driver in ${iftype:-$DRIVERS}; do (
		if eval "type load_$driver" 2>/dev/null >/dev/null; then
			eval "load_$driver" "$2" || echo "$driver: load failed" >&2
		else
			echo "$driver: wifi load not supported" >&2
		fi
	); done
	_wifi_updown "enable" "$1" "$2"
}

start_net() {(
	local iface="$1"
	local config="$2"
	local vifmac="$3"

	[ -f "/var/run/$iface.pid" ] && kill "$(cat /var/run/${iface}.pid)" 2>/dev/null
	[ -z "$config" ] || {
		include /lib/network
		scan_interfaces
		for config in $config; do
			unbridge "$iface" "$config"
			setup_interface "$iface" "$config" "" "$vifmac"
		done
	}
)}

set_wifi_up() {
	local cfg="$1"
	local ifname="$2"
	uci_set_state wireless "$cfg" up 1
	uci_set_state wireless "$cfg" ifname "$ifname"
}

set_wifi_down() {
	local cfg="$1"
	local vifs vif vifstr

	[ -f "/var/run/wifi-${cfg}.pid" ] &&
		kill "$(cat "/var/run/wifi-${cfg}.pid")" 2>/dev/null
	uci_revert_state wireless "$cfg"
	config_get vifs "$cfg" vifs
	for vif in $vifs; do
		uci_revert_state wireless "$vif"
	done
}

scan_wifi() {
	local cfgfile="$1"
	DEVICES=
	MLD_DEVICES=
	config_cb() {
		local type="$1"
		local section="$2"

		# section start
		case "$type" in
			wifi-device)
				append DEVICES "$section"
				config_set "$section" vifs ""
				config_set "$section" ht_capab ""
			;;
		esac

		# section end
		config_get TYPE "$CONFIG_SECTION" TYPE
		case "$TYPE" in
			wifi-iface)
				config_get device "$CONFIG_SECTION" device
				config_get vifs "$device" vifs
				append vifs "$CONFIG_SECTION"
				config_set "$device" vifs "$vifs"
			;;
			wifi-mld)
				append MLD_DEVICES "$CONFIG_SECTION"
			;;
		esac
	}
	config_load "${cfgfile:-wireless}"
}

wifi_log() {
	local comm="wifi $@"
	local ppid="$$"
	while [ "$ppid" -gt 1 ]
	do
		ppid=$(cat /proc/"$ppid"/status | grep "PPid" | awk '{print $2}')
		comm="$(cat /proc/$ppid/comm)""[$ppid]-->"${comm}
	done
	logger -t "wireless" -s  "$comm"
	echo "$(date '+%F %X') $comm" >> /tmp/wifi.log
}

wifi_log "$@"

DEVICES=
MLD_DEVICES=
DRIVERS=
(
	flock 300

	trap clean_flock INT TERM EXIT KILL STOP ABRT QUIT ALRM
	clean_flock() {
		# for qca
		for driver in ${1:-$DRIVERS}; do (
			if eval "type trap_$driver" 2>/dev/null >/dev/null; then
				eval "trap_$driver" >&2
			fi
		); done

		flock -u 300

		rm -rf /var/lock/wifi.lock

		exit
	}

	include /lib/wifi
	scan_wifi

	case "$1" in
		down) wifi_updown "disable" "$2" "$3";;
		stop) wifi_iface "stop" "$2";;
		start) wifi_iface "start" "$2";;
		detect) wifi_detect ;;
		config) wifi_config "$2";;
		status) ubus_wifi_cmd "status" "$2";;
		reload) wifi_reload "$2" "wifi_reload";;
		reload_legacy) wifi_reload_legacy "$2" "" "$1" "$3";;
		event_reload_legacy) event_wifi_updown "enable" "$2";;
		load) wifi_load "$2" "wifi_load";;
		unload) wifi_unload "$2";;
		recover) wifi_recover "$2";;
		mlo) mlo "$@";;
		--help|help) usage;;
		''|up) ubus call network reload; wifi_updown "enable" "$2" "$3" "wifi_up";;
		*) usage; exit 1;;
	esac
) 300>/var/lock/wifi.lock

rm -rf /var/lock/wifi.lock
